FROM node:20.18.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g pnpm@latest-10 --y

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4321

# Command to run the application
CMD ["pnpm", "run", "dev"]