FROM node:20.18.0

# Set the working directory
WORKDIR /app

# Instalar pnpm globalmente
RUN npm install -g pnpm@latest

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4321

# Command to run the application
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]