#how to execute this file: docker-compose -f docker-compose-dev.yml up -d
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    container_name: website_backend_dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: website_frontend_dev
    ports:
      - "4321:4321" # Asegúrate de que el puerto esté correctamente mapeado
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
    networks:
      - default

networks:
  default:
    driver: bridge
