#how to execute this file: docker-compose -f docker-compose-dev.yml up -d
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: website-backend
    expose:
      - 3000 
    networks:
      - red_internal
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: website-frontend
    expose:
      - 4321 
    networks:
      - red_internal
    env_file:
      - ./.env
    environment:
      - PUBLIC_API_BASE_URL=http://website_backend:3000/api
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    container_name: website-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"  # Solo expone el puerto del Nginx
    depends_on:
      - frontend
      - backend

networks:
  red_internal: